stages:
  - Checks
  - Image


Sign-off check:
  stage: Checks
  image: python:3.7-alpine
  script:
    - apk add git
    - .gitlab-ci/signed-off-by-check > ${CI_PROJECT_DIR}/sign-off-report.xml
  artifacts:
    reports:
      junit: sign-off-report.xml


Image:
  stage: Image
  image: docker:latest
  script:
    - chmod og-w . -R
    - apk add --no-cache bash
    - ./scripts/build-image
  variables:
    IMG: img-${CI_JOB_ID}-ce

